### ISSUE TITLE
many dependencies don't render correctly

### ISSUE THREAD

**Issue by weissi** [adam-fowler/swift-dependency-graph#1]
If you look at a project with many dependents, the rendering is a bit off. For example check all the packages that depend on `swift-nio`. If you scroll far enough to the right it looks like this :).

![Screenshot 2020-01-20 at 4 05 04 pm](https://user-images.githubusercontent.com/624238/72740970-a063fb80-3b9e-11ea-9c93-ea5cb96360e1.png)

**Comment by adam-fowler** [comment]
Yeah that a problem with those trouble maker projects like swift-nio :-)
There is an inaccuracy in the google charts output, haven't really had time to look at this recently. Also recent changes in the SPM project have broken my packet dependency creation so the list is out of date.

**Comment by weissi** [comment]
no worries at all, just wanted to be sure you're aware :)

**Comment by adam-fowler** [comment]
@weissi cheers

**Comment by adam-fowler** [comment]
Fixed by paging results. 
Projects with large numbers of dependents will only show 16 dependents at a time. Next and prev blocks are added to move between blocks
